### ISSUE TITLE
SolveStatistics의 'rate' 필드가 필요한가

### ISSUE THREAD

**Issue by tnRaro** [ice-judge/ICE-api#1]
[문제 헤더](https://github.com/ice-judge/ICE-api/blob/master/doc/schema/problems.md) 문서의 SolveStatistics 파트에 'rate' 필드가 있다. 이 값이 필요한지 의문.

**Comment by sunho** [comment]
디비에서 rate 저장하고 이를 인덱싱할 생각이기에 넣어놨습니다. 더러워 보이신다면 뺄 수도 있음.

**Comment by tibyte** [comment]
스키마 설계 전체적으로 한번 검토해야겠네요 뭔가 이상합니다..
그리고 rate는 자주 변하는 값이기에 rdb에서 인덱싱하는거보다 레디스같은 인메모리 디비에 넣죠

**Comment by sunho** [comment]
넹 이상한 점 있으시면 바로바로 지적해주세요
